name: PaperBoilerplate
main: com.liamxsage.boilerplates.PaperBoilerplate
version: 1.20.6
description: "This is a template for a new plugin based on Paper and the new Minecraft API."
author: "LiamXSage"
api-version: "1.20"
loader: com.liamxsage.boilerplates.DependencyLoader